name: Update Quotes

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every day at 12 AM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout workflow branch
      uses: actions/checkout@v2
      with:
        ref: workflow
        fetch-depth: 0
        
    - name: Create and checkout temp branch
      run: git checkout -b temp
      
    - name: Verify identity
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        # git config --global core.editor "nano"

    - name: Merge main into temp with conflict resolution
      run: |
          git commit -m "Remove gitignore" || exit 0
          git merge origin/main --no-commit
          # Resolve conflicts manually, if any, in your working directory
          # Once conflicts are resolved, add the resolved files
          git rm .gitignore
  
      shell: bash

    - name: Log current directory
      run: |
        ls -lahrS

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10' # Use the version of Node.js that your script requires

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci # or use 'npm install' if you don't have a lock file

    - name: Run quote generator
      run: node index.js
    
    - name: Remove workflow direcotries
      run: |
        rm -rf node_modules
        rm package*.json
        rm -rf .gitignore 
        rm -rf index.js
        rm -rf dist
        
    - name: Commit and push if changed
      run: |
        git add README.md
        git commit -m "Update README\nPushed by actions@github.com" || exit 0
        ls -lahrS
        git push -f -u origin main

    - name: Delete temporary branch
      run: git branch -d temp