name: Update Quotes

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Clone main branch
        uses: actions/checkout@v2
        with:
          ref: main # Checkout the main branch
          path: main # Specify a subdirectory for the main branch

          
      - name: Switch to workflow branch
        uses: actions/checkout@v2
        with:
          ref: workflow  # Checkout the main branch
          path: workflow # Specify a subdirectory for the main branch
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd workflow
          npm ci

      - name: Run JavaScript script
        run: |
          cd workflow
          node index.js

      - name: Transfer readme
        run: |
          cd workflow
          mv -f README.md ../main/README.md
          cd ../main
          ls . -lahrS 

      - name: Commit and push changes
        run: |
          cd main
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git add .github
          # # Add more git add commands for other necessary files
          git commit -m "Daily readme update!" || exit 0 # Don't fail if nothing to commit
          git push # Push changes to the workflow branch
