name: Update Quotes

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every day at 12 AM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout workflow branch
      uses: actions/checkout@v2
      with:
        ref: workflow
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10' # Use the version of Node.js that your script requires

    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Pull info
      run: |
        git pull origin main
        ls

    - name: Install dependencies
      run: npm ci # or use 'npm install' if you don't have a lock file

    - name: Get quotes and update README
      run: node index.js

    - name: Config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git config --global advice.addIgnoredFile false

    - name: Commit changes
      run: |
          git diff
          git add README.md
          git commit -m "Update README\nPushed by github actions" || exit 0

    - name:
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0

    - name: Remove files
      run: |
          ls
          rm -rf .dist
          rm -rf node_modules
          rm -rf .gitignore
          rm -rf index.js
          rm -rf package.json
          rm -rf package-lock.json

    - name: Push updates
      run: |
          git push